"""Add 2FA OTP fields to users table

Revision ID: 40b530679fa3
Revises: 7d85d4c05a36
Create Date: 2025-05-16 01:05:22.030732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b530679fa3'
down_revision: Union[str, None] = '7d85d4c05a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('is_otp_enabled', sa.Boolean(), nullable=False))
    op.add_column('tenants', sa.Column('encrypted_otp_secret', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'encrypted_otp_secret')
    op.drop_column('tenants', 'is_otp_enabled')
    # ### end Alembic commands ###
