"""Add odoo_employee_id to users table

Revision ID: 7e3927cfd66c
Revises: 39dc5c3b20c3
Create Date: 2025-05-06 12:00:28.407801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e3927cfd66c'
down_revision: Union[str, None] = '39dc5c3b20c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('odoo_employee_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_odoo_employee_id'), 'users', ['odoo_employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_odoo_employee_id'), table_name='users')
    op.drop_column('users', 'odoo_employee_id')
    # ### end Alembic commands ###
